"""Report generator for creating Markdown reports.

This module provides utilities for generating structured Markdown reports
from foresight_manager and portfolio_manager.
"""

from datetime import datetime
from pathlib import Path

from midas.config import DATA_DIR

# Report output directory
REPORTS_DIR = DATA_DIR / "reports"


def ensure_reports_dir() -> Path:
    """Ensure the reports directory exists."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    return REPORTS_DIR


def generate_report_filename(report_type: str, suffix: str = "") -> str:
    """Generate a timestamped report filename.

    Args:
        report_type: Type of report (e.g., 'foresight', 'portfolio')
        suffix: Optional suffix for the filename

    Returns:
        Filename string like 'foresight_20260104_143022.md'
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    if suffix:
        return f"{report_type}_{suffix}_{timestamp}.md"
    return f"{report_type}_{timestamp}.md"


def save_report(content: str, report_type: str, suffix: str = "") -> Path:
    """Save a Markdown report to the reports directory.

    Args:
        content: Markdown content to save
        report_type: Type of report
        suffix: Optional suffix for the filename

    Returns:
        Path to the saved report
    """
    ensure_reports_dir()
    filename = generate_report_filename(report_type, suffix)
    filepath = REPORTS_DIR / filename

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath


# =============================================================================
# Foresight Report Generation
# =============================================================================


def generate_foresight_report(
    foresights: list[dict],
    executive_summary: str = "",
    period: str = "",
) -> str:
    """Generate a Markdown report for foresights.

    Args:
        foresights: List of foresight dictionaries
        executive_summary: Executive summary text
        period: Analysis period description

    Returns:
        Markdown content string
    """
    lines = [
        "# Foresight Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
    ]

    if period:
        lines.append(f"**Period:** {period}")

    lines.append("")

    # Executive Summary
    if executive_summary:
        lines.extend([
            "## Executive Summary",
            "",
            executive_summary,
            "",
        ])

    # Foresights
    lines.extend([
        "## Foresights",
        "",
    ])

    if not foresights:
        lines.append("*No foresights available.*")
    else:
        for i, foresight in enumerate(foresights, 1):
            title = foresight.get("title", f"Foresight {i}")
            description = foresight.get("description", "")
            sources = foresight.get("sources", [])

            lines.extend([
                f"### {i}. {title}",
                "",
                description,
                "",
            ])

            if sources:
                lines.append("**Sources:**")
                for source in sources[:5]:
                    source_title = source.get("title", "Unknown")
                    source_url = source.get("url", "")
                    if source_url:
                        lines.append(f"- [{source_title}]({source_url})")
                    else:
                        lines.append(f"- {source_title}")
                lines.append("")

    # Footer
    lines.extend([
        "---",
        "",
        "*Generated by Midas Investment Analysis System*",
    ])

    return "\n".join(lines)


# =============================================================================
# Portfolio Report Generation
# =============================================================================


def generate_portfolio_report(
    holdings: list[dict],
    analysis: dict | None = None,
    recommendations: list[str] | None = None,
) -> str:
    """Generate a Markdown report for portfolio analysis.

    Args:
        holdings: List of holding dictionaries
        analysis: Analysis results dictionary
        recommendations: List of recommendation strings

    Returns:
        Markdown content string
    """
    lines = [
        "# Portfolio Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]

    # Portfolio Overview
    lines.extend([
        "## Portfolio Overview",
        "",
    ])

    if not holdings:
        lines.append("*No holdings in portfolio.*")
    else:
        # Summary table
        lines.extend([
            "| Symbol | Name | Shares | Avg Cost | Current | Gain/Loss |",
            "|--------|------|--------|----------|---------|-----------|",
        ])

        total_cost = 0.0
        total_value = 0.0

        for h in holdings:
            symbol = h.get("symbol", "")
            name = h.get("name", "")[:20]
            shares = h.get("shares", 0)
            avg_cost = h.get("avg_cost", 0)
            current_price = h.get("current_price")

            total_cost += shares * avg_cost

            if current_price:
                current_value = shares * current_price
                total_value += current_value
                gain = current_value - (shares * avg_cost)
                gain_pct = (gain / (shares * avg_cost) * 100) if avg_cost else 0
                gain_str = f"{gain:+,.0f} ({gain_pct:+.1f}%)"
                current_str = f"${current_price:,.2f}"
            else:
                gain_str = "N/A"
                current_str = "N/A"

            lines.append(
                f"| {symbol} | {name} | {shares:,} | ${avg_cost:,.2f} | {current_str} | {gain_str} |"
            )

        lines.append("")

        # Totals
        if total_value > 0:
            total_gain = total_value - total_cost
            total_gain_pct = (total_gain / total_cost * 100) if total_cost else 0
            lines.extend([
                f"**Total Cost:** ${total_cost:,.0f}",
                f"**Total Value:** ${total_value:,.0f}",
                f"**Total Gain/Loss:** ${total_gain:+,.0f} ({total_gain_pct:+.1f}%)",
                "",
            ])

    # Analysis
    if analysis:
        lines.extend([
            "## Analysis",
            "",
        ])

        overall = analysis.get("overall_assessment", "")
        if overall:
            lines.extend([
                "### Overall Assessment",
                "",
                overall,
                "",
            ])

        concentration = analysis.get("concentration_risk", "")
        if concentration:
            lines.extend([
                "### Concentration Risk",
                "",
                concentration,
                "",
            ])

        diversification = analysis.get("diversification", "")
        if diversification:
            lines.extend([
                "### Diversification",
                "",
                diversification,
                "",
            ])

        # Per-holding analysis
        holding_analysis = analysis.get("holding_analysis", [])
        if holding_analysis:
            lines.extend([
                "### Individual Holdings",
                "",
            ])
            for ha in holding_analysis:
                symbol = ha.get("symbol", "Unknown")
                assessment = ha.get("assessment", "")
                thesis_status = ha.get("thesis_status", "")
                lines.extend([
                    f"**{symbol}**",
                    "",
                    f"- Assessment: {assessment}",
                    f"- Thesis Status: {thesis_status}",
                    "",
                ])

    # Recommendations
    if recommendations:
        lines.extend([
            "## Recommendations",
            "",
        ])
        for rec in recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    # Footer
    lines.extend([
        "---",
        "",
        "*Generated by Midas Investment Analysis System*",
    ])

    return "\n".join(lines)


# =============================================================================
# Combined Report Generation
# =============================================================================


def generate_combined_report(
    foresights: list[dict] | None = None,
    holdings: list[dict] | None = None,
    portfolio_analysis: dict | None = None,
    buy_candidates: list[dict] | None = None,
    sell_alerts: list[dict] | None = None,
) -> str:
    """Generate a comprehensive combined report.

    Args:
        foresights: List of foresight dictionaries
        holdings: List of holding dictionaries
        portfolio_analysis: Portfolio analysis results
        buy_candidates: Companies to consider buying
        sell_alerts: Holdings that may need to be sold

    Returns:
        Markdown content string
    """
    lines = [
        "# Midas Investment Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "---",
        "",
    ]

    # Foresights Section
    if foresights:
        lines.extend([
            "## 1. Foresight (未来予測)",
            "",
        ])
        for i, f in enumerate(foresights[:5], 1):
            title = f.get("title", f"Foresight {i}")
            desc = f.get("description", "")[:200]
            lines.extend([
                f"### {i}. {title}",
                "",
                desc + ("..." if len(f.get("description", "")) > 200 else ""),
                "",
            ])

    # Portfolio Section
    if holdings:
        lines.extend([
            "## 2. Portfolio Status",
            "",
            "| Symbol | Shares | Value | Gain/Loss |",
            "|--------|--------|-------|-----------|",
        ])
        for h in holdings[:10]:
            symbol = h.get("symbol", "")
            shares = h.get("shares", 0)
            current = h.get("current_price", 0)
            avg_cost = h.get("avg_cost", 0)
            if current and avg_cost:
                value = shares * current
                gain_pct = ((current - avg_cost) / avg_cost * 100)
                lines.append(f"| {symbol} | {shares:,} | ${value:,.0f} | {gain_pct:+.1f}% |")
            else:
                lines.append(f"| {symbol} | {shares:,} | N/A | N/A |")
        lines.append("")

    # Buy Candidates
    if buy_candidates:
        lines.extend([
            "## 3. Buy Candidates (買い候補)",
            "",
        ])
        for c in buy_candidates[:5]:
            name = c.get("name", "Unknown")
            symbol = c.get("symbol", "")
            reason = c.get("reason", "")
            lines.extend([
                f"### {name} ({symbol})",
                "",
                reason,
                "",
            ])

    # Sell Alerts
    if sell_alerts:
        lines.extend([
            "## 4. Sell Alerts (売却検討)",
            "",
        ])
        for a in sell_alerts:
            symbol = a.get("symbol", "Unknown")
            reason = a.get("reason", "")
            severity = a.get("severity", "medium")
            lines.extend([
                f"### ⚠️ {symbol} [{severity.upper()}]",
                "",
                reason,
                "",
            ])

    # Footer
    lines.extend([
        "---",
        "",
        "*Generated by Midas Investment Analysis System*",
    ])

    return "\n".join(lines)
